# Dockerfile.cloud-run
FROM gcr.io/leangcp-317022/face-recognizer-base:latest

# workdir
WORKDIR /app

# copy
COPY main.py .
COPY generate_cache.py .

# create cache dir
ENV CACHE_DIR=/app/face_cache
RUN mkdir -p ${CACHE_DIR}

# copy cache files
COPY face_cache/ ${CACHE_DIR}/

# expose port
EXPOSE 8080

# 環境変数の設定
ENV PORT=8080

# サーバー起動コマンド
CMD exec functions-framework --target=face_recognizer --port=${PORT}